apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksusernamecni-fbb1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksusernamecni-fbb1"
  template:
    metadata:
      labels:
        app: "aksusernamecni-fbb1"
    spec:
      containers:
        - name: "aksusernamecni-fbb1"
          image: "acr2647.azurecr.io/aksusernamecni"
          ports:
          - containerPort: 80